### ISSUE TITLE
Why is SQW connected to RST, instead of the more usual pin 2?

### ISSUE THREAD

**Issue by samuelwhiskeyjohnson** [Naguissa/uRTCLib#33]
Just curious, for setting up the alarm,
why is SQW connected to RST, instead of the more usual pin 2 as interrupt pin?

**Comment by Naguissa** [comment]
It's also possible. Done this way in order to simplify the example, as it runs on 3 types of MCUs with different capabilities.

**Comment by samuelwhiskeyjohnson** [comment]
Thanks for your reply
1. Are you saying I can use the deep sleep example by simply connecting to the pin 2? or is it hard coded in your library that users can ONLY use the RST pin?
[uRTCLib_deepsleep.ino](https://github.com/Naguissa/uRTCLib/blob/master/examples/uRTCLib_deepsleep/uRTCLib_deepsleep.ino)

2. Do I still need the10uF capacitor if I use pin 2? Or why use capacitor at all for RST pin too? I'm just curious because I've seen other RTC libraries just connect pin 2 to RTC directly without the capacitor.

**Comment by Naguissa** [comment]
You can test it on Arduino using LowPower library: https://github.com/arduino-libraries/ArduinoLowPower/blob/master/examples/ExternalWakeup/ExternalWakeup.ino

In this case you will probably not need the capacitor. The capacitor is used to 'release' RST pin, as MCU doesn't restart until released.

**Comment by Naguissa** [comment]
Also, if you want to use alarm again, remember to use alarmClearFlag() : https://naguissa.github.io/uRTCLib_doc_and_extras/classuRTCLib.html#a1832bbb5322fbe2895c14132e559e03a

**Comment by samuelwhiskeyjohnson** [comment]
Hi thanks again for reply.
1. What do you mean by "The capacitor is used to 'release' RST pin, as MCU doesn't restart until released"?
At least for Arduino uno you don't need to release the RST pin? As long you send low signal for more than 2 micro seconds it restarts the Arduino.

2. Does the rtc.alarmSet() send a pulse of low signal or toggles to low signal? I thought it toggles to low signal hence why you need alarmClearFlag() to toggle back to high.

**Comment by Naguissa** [comment]
Hello again!

I reply in inverse order, as it's more logical:

 - 2 - RTC alarm toggles LOW SQWG pin on itself. It's how it works and it's useful to differentiate alarms and pulses generated by the generator. Hence the name (negated)INT / SQWG: https://github.com/Naguissa/uRTCLib_doc_and_extras/blob/master/extras/DS3231.pdf


 - 1 - That's why you need the capacitor on RESET pin, as MCU will never restart if RST is directly connected to SQWG, it will be always LOW. Also, in order to reuse alarms, you ALWAYS need to clearAlarm().
